#!/bin/bash -f

# Configuration Variables
MODKEY=Mod4
UP=k
DOWN=j
LEFT=h
RIGHT=l

# Colors tuples: "<text> <background> <border>"
WMII_NORMCOLORS='#888888 #222222 #333333'
WMII_FOCUSCOLORS='#ffffff #285577 #4c7899'

WMII_BACKGROUND='#333333'
WMII_FONT='-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'

WMII_SLOW_TERM="evilvte"
WMII_TERM="xterm"
#WMII_FAST_TERM="SHELL=/bin/sh xterm"

# Column Rules
wmiir write /colrules <<!
/.*/ -> 62+38
!

# Tagging Rules
wmiir write /tagrules <<!
/.*Lanikai.*/ -> 8
/.*Namoroka.*/ -> 1
/.*Netsurf.*/ -> 1
/.*Pidgin.*/ -> 7
/Transmission/ -> 9
/.*/ -> sel
!

incr () {
    echo $(($(cat $1) + 1)) >$1
}

decr () {
    echo $(($(cat $1) - 1)) >$1
}


local_events() {
	cat <<'!'

# Status bar
Action status
    set +xv
    if wmiir remove /rbar/status 2>/dev/null; then
        sleep 2
    fi
    PYTHONPATH=~/.syspath ~/.wmii/statusbar.py 3 >> ~/sys/logs/wmii

# Terminals
#Key $MODKEY-Return
#    eval $WMII_FAST_TERM &
Key $MODKEY-Control-Return
    eval $WMII_SLOW_TERM &
Key $MODKEY-Return
    eval $WMII_TERM &

# moc
Key $MODKEY-n
    mocp --next
Key $MODKEY-b
    mocp --previous
Key $MODKEY-v
    mocp --toggle-pause

# Keyboard resize
Key $MODKEY-Control-$LEFT
    wmiir xwrite /tag/sel/ctl grow sel sel right -3
Key $MODKEY-Control-$RIGHT
    wmiir xwrite /tag/sel/ctl grow sel sel right 3
Key $MODKEY-Control-$DOWN
    wmiir xwrite /tag/sel/ctl grow sel sel down 3
Key $MODKEY-Control-$UP
    wmiir xwrite /tag/sel/ctl grow sel sel down -3

# special keys
Key $MODKEY-F1
    amixer -q set PCM 3%-
Key Xf86AudioLowerVolume
    amixer -q set PCM 3%-
Key $MODKEY-F2
    amixer -q set PCM 3%+
Key Xf86AudioRaiseVolume
    amixer -q set PCM 3%+
Key $MODKEY-F3
    amixer set PCM toggle
Key Xf86AudioMute
    amixer set PCM toggle
Key $MODKEY-F4
    decr /sys/class/backlight/acpi_video0/brightness
Key $MODKEY-F5
    incr /sys/class/backlight/acpi_video0/brightness
Key $MODKEY-F12
    setxkbmap us
Key $MODKEY-F11
    setxkbmap de
Key $MODKEY-F9
    sudo pm-suspend
!
}
