#!/bin/bash -f

# Configuration Variables
MODKEY=Mod4
UP=k
DOWN=j
LEFT=h
RIGHT=l

# Colors tuples: "<text> <background> <border>"
WMII_NORMCOLORS='#888888 #222222 #333333'
WMII_FOCUSCOLORS='#ffffff #285577 #4c7899'

WMII_BACKGROUND='#333333'
WMII_FONT='-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'

WMII_TERM="xterm"
#WMII_FAST_TERM="SHELL=/bin/sh xterm"

# Column Rules
wmiir write /colrules <<!
/.*/ -> 62+38
!

# Tagging Rules
wmiir write /tagrules <<!
/.*dwb.*/ -> 1
/.*Thunderbird.*/ -> 8
/.*Chromium.*/ -> 1
/.*Netsurf.*/ -> 1
/.*Pidgin.*/ -> 7
/Transmission/ -> 9
/.*/ -> sel
!

toggle_touchpad() {
  if synclient | grep Touchpad | grep 1
    then synclient TouchpadOff=0
    else synclient TouchpadOff=1
  fi
}

local_events() {
	cat <<'!'
# Status bar
Action status
    set +xv
    if wmiir remove /rbar/status 2>/dev/null; then
        sleep 2
    fi
    ~/.wmii/statusbar.py >> /tmp/logs/wmii

# Various stuff
Key $MODKEY-o      # Open program menu
	eval wmiir setsid "$(wimenu -h "${hist}.progs" -n $histnum <$progsfile)" &
Key $MODKEY-Q
    eval wmiir setsid $WMII_TERM &
Key $MODKEY-c
    xclip -o | xclip -sel C

# moc
Key XF86AudioNext
    mocp --next
Key XF86AudioPrev
    mocp --previous
Key XF86AudioPlay
    mocp --toggle-pause
Key XF86AudioStop
    mocp --exit

# Keyboard resize
Key $MODKEY-Control-$LEFT
    wmiir xwrite /tag/sel/ctl grow sel sel right -3
Key $MODKEY-Control-$RIGHT
    wmiir xwrite /tag/sel/ctl grow sel sel right 3
Key $MODKEY-Control-$DOWN
    wmiir xwrite /tag/sel/ctl grow sel sel down 3
Key $MODKEY-Control-$UP
    wmiir xwrite /tag/sel/ctl grow sel sel down -3

# special keys
Key $MODKEY-F1
    amixer -q set PCM 5%-
Key XF86AudioLowerVolume
    amixer -q set PCM 5%-
Key $MODKEY-F2
    amixer -q set PCM 5%+
Key XF86AudioRaiseVolume
    amixer -q set PCM 5%+
Key $MODKEY-F3
    amixer set Master toggle
Key XF86AudioMute
    amixer set Master toggle
Key XF86TouchpadToggle
    toggle_touchpad
Key XF86Sleep
    sudo pm-suspend &
!
}
