#!/bin/sh

DEFAULT_XENV='wmii'

if [ -z $1 ]; then
  XENV=$DEFAULT_XENV
else
  XENV=$1
fi

rm ~/.xinitrc
ln -s ~/.xinitrc.$XENV ~/.xinitrc
startx > ~/.logs/X 2>&1 &

~/.bin/autostart &
.bin/x-session &
